### ISSUE TITLE
compiler error with model_logit_cov2

### ISSUE THREAD

**Issue by bgoodri** [artemis-toumazi/dfpk#2]
With versions 2.13.x of StanHeaders and rstan --- which will soon be on CRAN --- dfpk will experience a compiler error that looks like

```
include/models.hpp: In member function ‘T__ model_logit_cov2_namespace::model_logit_cov2::log_prob(std::vector<T2>&, std::vector<int>&, std::ostream*) const’:
include/models.hpp:256:102: error: call of overloaded ‘fmax(int, double)’ is ambiguous
                 lp_accum__.add(uniform_log<propto__>(get_base1(bet,2,"bet",1), fmax(0,(beta1mean - 5)), (beta1mean + 5)));
```

An easy solution to this problem is to use floating point numbers with no non-zero decimal places rather than integers in your .stan files. For example, in 
https://github.com/artemis-toumazi/dfpk/blob/master/exec/logit_cov2.stan#L29
do
```
 bet[2] ~ uniform(fmax(0.0, beta1mean - 5), beta1mean + 5);
```

A similar fix will be needed for logit_reg_dtox.stan.

While we don't recommend uniform priors, if you are going to use them, it is necessary to impose the constraints in the `parameters` block rather than the `model` block, and it would be better if the bounds were passed in through the `data` block rather than hard-coded (e.g. - / + 5).

**Comment by artemis-toumazi** [comment]
Hello,

Thanks for reporting this to me. I'll make sure to fix this in the following days with the new version of dfpk.
